export type IconGlyph =
  | 'chart-gantt'
  | 'chevron-left'
  | 'clock'
  | 'cross'
  | 'delivery'
  | 'donut-classic'
  | 'donut-decadent'
  | 'donut-filled'
  | 'donut-fruity'
  | 'donut-nutty'
  | 'flag'
  | 'flame'
  | 'heart'
  | 'heart-filled'
  | 'map-pin'
  | 'menu'
  | 'minus'
  | 'newspaper'
  | 'phone'
  | 'plus'
  | 'search'
  | 'settings'
  | 'shopping-bag'
  | 'star'
  | 'star-filled'
  | 'tool-case'
  | 'truck-electric'
  | 'user'

export const glyphMap: Record<IconGlyph, string> = {
  'chart-gantt': '\uE001',
  'chevron-left': '\uE002',
  clock: '\uE003',
  cross: '\uE004',
  delivery: '\uE005',
  'donut-classic': '\uE006',
  'donut-decadent': '\uE007',
  'donut-filled': '\uE008',
  'donut-fruity': '\uE009',
  'donut-nutty': '\uE00A',
  flag: '\uE00B',
  flame: '\uE00C',
  heart: '\uE00E',
  'heart-filled': '\uE00D',
  'map-pin': '\uE00F',
  menu: '\uE010',
  minus: '\uE011',
  newspaper: '\uE012',
  phone: '\uE013',
  plus: '\uE014',
  search: '\uE015',
  settings: '\uE016',
  'shopping-bag': '\uE017',
  star: '\uE019',
  'star-filled': '\uE018',
  'tool-case': '\uE01A',
  'truck-electric': '\uE01B',
  user: '\uE01C',
}
