/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as ProfileRouteImport } from './profile'
import { Route as OrdersRouteImport } from './orders'
import { Route as OnboardingRouteImport } from './onboarding'
import { Route as HomeRouteImport } from './home'
import { Route as CatalogRouteImport } from './catalog'
import { Route as CartRouteImport } from './cart'
import { Route as BookmarksRouteImport } from './bookmarks'
import { Route as IndexRouteImport } from './index'
import { Route as ProductDonutIdRouteImport } from './product.$donutId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDonutIdRoute = ProductDonutIdRouteImport.update({
  id: '/product/$donutId',
  path: '/product/$donutId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/product/$donutId': typeof ProductDonutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/product/$donutId': typeof ProductDonutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/product/$donutId': typeof ProductDonutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/cart'
    | '/catalog'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/product/$donutId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/cart'
    | '/catalog'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/product/$donutId'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/cart'
    | '/catalog'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/product/$donutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ProductDonutIdRoute: typeof ProductDonutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$donutId': {
      id: '/product/$donutId'
      path: '/product/$donutId'
      fullPath: '/product/$donutId'
      preLoaderRoute: typeof ProductDonutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ProductDonutIdRoute: ProductDonutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
