import type { Review } from '../model/types'

export const reviews: Review[] = [
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=12',
    authorName: 'John Doe',
    date: '2 weeks ago',
    donutId: '1',
    id: 'r1',
    rating: 4,
    text: 'Rich chocolate glaze with the perfect amount of sprinkles. Absolutely loved it!',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=25',
    authorName: 'Sarah Miller',
    date: '1 month ago',
    donutId: '1',
    id: 'r2',
    rating: 5,
    text: 'Best chocolate donut I have ever had. The glaze is heavenly and the donut itself is so fluffy.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=7',
    authorName: 'Kevin Hart',
    date: '3 days ago',
    donutId: '1',
    id: 'r1a',
    rating: 5,
    text: 'Ordered a dozen for my office and they were gone in minutes. The chocolate glaze is perfection.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=9',
    authorName: 'Olivia Brown',
    date: '5 days ago',
    donutId: '1',
    id: 'r1b',
    rating: 4,
    text: 'Really solid donut. The sprinkles add a nice crunch to the smooth chocolate coating.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=11',
    authorName: 'Daniel Lee',
    date: '1 week ago',
    donutId: '1',
    id: 'r1c',
    rating: 5,
    text: 'This is my go-to donut every Saturday morning. Never disappoints!',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=14',
    authorName: 'Emma Watson',
    date: '2 weeks ago',
    donutId: '1',
    id: 'r1d',
    rating: 3,
    text: 'Good but a bit too sweet for my taste. The chocolate is high quality though.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=17',
    authorName: 'Marcus Johnson',
    date: '3 weeks ago',
    donutId: '1',
    id: 'r1e',
    rating: 5,
    text: 'Hands down the best donut in town. Crispy outside, soft inside, perfect glaze.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=20',
    authorName: 'Priya Patel',
    date: '1 month ago',
    donutId: '1',
    id: 'r1f',
    rating: 4,
    text: 'Great texture and flavor. My kids absolutely love these chocolate donuts.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=23',
    authorName: 'Carlos Rivera',
    date: '1 month ago',
    donutId: '1',
    id: 'r1g',
    rating: 5,
    text: 'Fresh and delicious every single time. The chocolate is rich without being overwhelming.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=33',
    authorName: 'Mike Chen',
    date: '3 days ago',
    donutId: '2',
    id: 'r3',
    rating: 4,
    text: 'Cream filling was smooth and not too sweet. Great balance of flavors.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=47',
    authorName: 'Emily Rose',
    date: '1 week ago',
    donutId: '2',
    id: 'r4',
    rating: 5,
    text: 'The custard filling is incredible. Tastes like it was made fresh this morning.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=15',
    authorName: 'Alex Kim',
    date: '5 days ago',
    donutId: '3',
    id: 'r5',
    rating: 5,
    text: 'The cream cheese frosting is to die for. Perfectly paired with the cinnamon spice.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=52',
    authorName: 'Lisa Park',
    date: '2 weeks ago',
    donutId: '3',
    id: 'r6',
    rating: 4,
    text: 'Loved the cinnamon flavor combination. Would definitely order again.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=60',
    authorName: 'James Wilson',
    date: '4 days ago',
    donutId: '4',
    id: 'r7',
    rating: 5,
    text: 'Triple chocolate heaven! The dark ganache is rich and the cocoa nibs add great texture.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=22',
    authorName: 'Anna Lee',
    date: '1 week ago',
    donutId: '4',
    id: 'r8',
    rating: 4,
    text: 'Decadent is the perfect name for this donut. So rich and satisfying.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=35',
    authorName: 'Tom Brown',
    date: '3 weeks ago',
    donutId: '5',
    id: 'r9',
    rating: 4,
    text: 'Ring donut, Chocolate frosted topped with fondant and biscuit crush.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=41',
    authorName: 'Rachel Green',
    date: '2 days ago',
    donutId: '5',
    id: 'r10',
    rating: 5,
    text: 'The rainbow sprinkles make it so fun! Great classic donut with a twist.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=18',
    authorName: 'David Kim',
    date: '1 week ago',
    donutId: '6',
    id: 'r11',
    rating: 4,
    text: 'The honey drizzle with crushed nuts is amazing. Perfect balance of sweet and nutty.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=28',
    authorName: 'Sophie Turner',
    date: '5 days ago',
    donutId: '7',
    id: 'r12',
    rating: 4,
    text: 'Love the fresh berry flavor! Light and refreshing compared to heavy chocolate donuts.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=44',
    authorName: 'Chris Evans',
    date: '3 days ago',
    donutId: '8',
    id: 'r13',
    rating: 5,
    text: 'You cannot go wrong with the classic glazed. Simple perfection.',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=50',
    authorName: 'Mia Johnson',
    date: '1 month ago',
    donutId: '9',
    id: 'r14',
    rating: 5,
    text: 'The sea salt with caramel is a genius combination. Absolutely divine!',
  },
  {
    authorAvatar: 'https://i.pravatar.cc/48?img=55',
    authorName: 'Ryan Scott',
    date: '2 weeks ago',
    donutId: '10',
    id: 'r15',
    rating: 4,
    text: 'Pretty in pink and delicious too! The white chocolate chips are a nice touch.',
  },
]
